services:
  db:
    image: mysql:8.0
    container_name: tasker_db
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "tasker"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    container_name: tasker_api
    restart: always
    volumes:
      - ./api:/app
    environment:
      DB_URI: "root:@tcp(db:3306)/tasker?multiStatements=true"
      PORT: "3000"
      API_URL_PREPROD: "http://localhost:5173"
      API_URL_PROD: "http://localhost:4173"
    ports:
      - "3000:3000"
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    container_name: tasker_client
    restart: always
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      PUBLIC_API_URL: "http://localhost:3000"
      PORT: "3000"
      ORIGIN: "http://localhost:5173"
    ports:
      - "5173:5173"
    depends_on:
      - api

volumes:
  mysql_data:
